// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Servicios_personal_crossmotion.Models
{
    public partial class CatDepartamento
    {
        public CatDepartamento()
        {
            //Personal = new HashSet<Personal>();
        }

        public int IdDepartamento { get; set; }
        public string Departamento { get; set; }

        //public virtual ICollection<Personal> Personal { get; set; }
    }
}